version: "3.9"
services:
   postgres_cattledb:
      container_name: postgres_cattledb
      image: msuenkel/percom2022-postgres:latest
      networks:
         - percom2022-network
      ports:
         - "5432:5432"
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         PGDATA: /postgres
   odysseus_webstudio_frontend:
      container_name: odysseus_webstudio_frontend
      image: msuenkel/percom2022-odysseus-webstudio-frontend:latest
      networks:
         - percom2022-network
      ports:
         - "4200:80"
      environment:
         NODE_ENV: production
      restart: always
      depends_on:
         - backend
   odysseus_webstudio_backend:
      container_name: backend
      image: msuenkel/percom2022-odysseus-webstudio-backend:latest
      networks:
         - percom2022-network
      ports:
         - "3000:3000"
      environment:
         NODE_ENV: production
         MONGODB_URI: mongodb://odysseus_webstudio_mongo:27017/webstudio
         SECRET_TOKEN: jwtSecretToken
         DOWNLOAD_TOKEN: downloadToken
         PROJECTS_FOLDER: projects
      restart: always
      depends_on:
         - odysseus_webstudio_mongo
   odysseus_webstudio_mongo:
      container_name: odysseus_webstudio_mongo
      image: msuenkel/percom2022-odysseus-webstudio-mongo:latest
      networks:
         - percom2022-network
      ports:
         - "27017:27017"
      restart: always
   rpc_classification_1:
      container_name: rpc_classification_1
      image: msuenkel/percom2022-python-rpc-classification:latest
      networks:
         - percom2022-network
      ports:
         - "9001:9000"
      command: ["9000"]
   rpc_classification_2:
      container_name: rpc_classification_2
      image: msuenkel/percom2022-python-rpc-classification:latest
      networks:
         - percom2022-network
      ports:
         - "9002:9000"
      command: ["9000"]
   rpc_classification_3:
      container_name: rpc_classification_3
      image: msuenkel/percom2022-python-rpc-classification:latest
      networks:
         - percom2022-network
      ports:
         - "9003:9000"
      command: ["9000"]
   odysseus_sensor_data_19_eval:
      container_name: odysseus_sensor_data_19_eval
      image: msuenkel/percom2022-odysseus-server:latest
      networks:
         - percom2022-network
      ports:
         - "9101:8888"
   odysseus_sensor_data_20_eval:
      container_name: odysseus_sensor_data_20_eval
      image: msuenkel/percom2022-odysseus-server:latest
      networks:
         - percom2022-network
      ports:
         - "9102:8888"
   odysseus-fog:
      container_name: odysseus-fog
      image: msuenkel/percom2022-odysseus-server:latest
      networks:
         - percom2022-network
      ports:
         - "9103:8888"
   odysseus-cloud:
      container_name: odysseus-cloud
      image: msuenkel/percom2022-odysseus-server:latest
      networks:
         - percom2022-network
      ports:
         - "9104:8888"
networks:
   percom2022-network:
      name: percom2022-network