package percom.graph.operator;

import percom.graph.operator.meta.Operator;

public class AggregateOperator extends Operator
{
	public static final String QUERY = 
			  "aggregatedFeatures = AGGREGATE\r\n"
			+ "(\r\n"
			+ "\t{\r\n"
			+ "\t\tname = \"featureCalculation\",\r\n"
			+ "\t\tgroup_by = [\"cattle_id\"],\r\n"
			+ "\t\taggregations=\r\n"
			+ "\t\t[\r\n"
			+ "\t\t\t['count', ['Amag'], 'count', 'Integer'],\r\n"
			+ "\t\t\t['min', ['Amag'], 'accMag_min', 'Double'],\r\n"
			+ "\t\t\t['min', ['Gmag'], 'gyrMag_min', 'Double'],\r\n"
			+ "\t\t\t['max', ['Amag'], 'accMag_max', 'Integer'],\r\n"
			+ "\t\t\t['max', ['Gmag'], 'gyrMag_max', 'Double'],\r\n"
			+ "\t\t\t['avg', ['Amag'], 'accMag_mean', 'Double'],\r\n"
			+ "\t\t\t['avg', ['Gmag'], 'gyrMag_mean', 'Double'],\r\n"
			+ "\t\t\t['median', ['Amag'], 'accMag_median', 'Double'],\r\n"
			+ "\t\t\t['median', ['Gmag'], 'gyrMag_median', 'Double'],\r\n"
			+ "\t\t\t['STDDEV', ['Amag'], 'accMag_std', 'Double'],\r\n"
			+ "\t\t\t['STDDEV', ['Gmag'], 'gyrMag_std', 'Double'],\r\n"
			+ "\t\t\t['kurtosis', ['Amag'], 'accMag_kurt', 'Double'],\r\n"
			+ "\t\t\t['kurtosis', ['Gmag'], 'gyrMag_kurt', 'Double'],\r\n"
			+ "\t\t\t['skewness', ['Amag'], 'accMag_skew', 'Double'],\r\n"
			+ "\t\t\t['skewness', ['Gmag'], 'gyrMag_skew', 'Double'],\r\n"
			+ "\t\t\t['IQR', ['Amag'], 'accMag_IQR', 'Double'],\r\n"
			+ "\t\t\t['IQR', ['Gmag'], 'gyrMag_IQR', 'Double'],\r\n"
			+ "\t\t\t['MCR', ['Amag'], 'accMag_MCR', 'Double'],\r\n"
			+ "\t\t\t['MCR', ['Gmag'], 'gyrMag_MCR', 'Double'],\r\n"
			+ "\t\t\t['RMS', ['Amag'], 'accMag_RMS', 'Double'],\r\n"
			+ "\t\t\t['RMS', ['Gmag'], 'gyrMag_RMS', 'Double'],\r\n"
			+ "\t\t\t['FrEnergy', ['Amag'], 'accMag_FrEnergy', 'Double'],\r\n"
			+ "\t\t\t['FrEnergy', ['Gmag'], 'gyrMag_FrEnergy', 'Double'],\r\n"
			+ "\t\t\t['FrDmEntropy', ['Amag'], 'accMag_FrDmEntroPy', 'Double'],\r\n"
			+ "\t\t\t['FrDmEntropy', ['Gmag'], 'gyrMag_FrDmEntroPy', 'Double'],\r\n"
			+ "\t\t\t['FrPeakFreq', ['Amag'], 'accMag_FrPeakFreq', 'Double'],\r\n"
			+ "\t\t\t['FrPeakFreq', ['Gmag'], 'gyrMag_FrPeakFreq', 'Double'],\r\n"
			+ "\t\t\t['FrMag1', ['Amag'], 'accMag_FrMag1', 'Double'],\r\n"
			+ "\t\t\t['FrMag2', ['Amag'], 'accMag_FrMag2', 'Double'],\r\n"
			+ "\t\t\t['FrMag3', ['Amag'], 'accMag_FrMag3', 'Double'],\r\n"
			+ "\t\t\t['FrMag4', ['Amag'], 'accMag_FrMag4', 'Double'],\r\n"
			+ "\t\t\t['FrMag5', ['Amag'], 'accMag_FrMag5', 'Double'],\r\n"
			+ "\t\t\t['FrMag1', ['Gmag'], 'gyrMag_FrMag1', 'Double'],\r\n"
			+ "\t\t\t['FrMag2', ['Gmag'], 'gyrMag_FrMag2', 'Double'],\r\n"
			+ "\t\t\t['FrMag3', ['Gmag'], 'gyrMag_FrMag3', 'Double'],\r\n"
			+ "\t\t\t['FrMag4', ['Gmag'], 'gyrMag_FrMag4', 'Double'],\r\n"
			+ "\t\t\t['FrMag5', ['Gmag'], 'gyrMag_FrMag5', 'Double']\r\n"
			+ "\t\t]\r\n"
			+ "\t},\r\n"
			+ "\tsensorMagWindowed\r\n"
			+ ")";
}